name: Deploy eBook App to EC2

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Version & Commit Hash
        id: vars
        run: |
          VERSION="1.0.0"  # Manually update or automate
          COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_TAG="${VERSION}-${COMMIT_HASH}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      -- name: Deploy to EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}  # Your EC2 instance IP or domain
    username: ubuntu              # Your EC2 SSH username
    key: ${{ secrets.EC2_SSH_KEY }}  # The SSH private key (stored in GitHub secrets)
    script: |
      # Stop and remove the old container
      docker stop ebook-app || true
      docker rm ebook-app || true

      # Pull the latest Docker image (with the correct tag)
      docker pull naji611/ebook-app:${{ env.IMAGE_TAG }}

      # Run the new container
      docker run -d -p 3000:3000 --name ebook-app naji611/ebook-app:${{ env.IMAGE_TAG }}
